# Reconstruct bigsnp/bigpheno objects from the internal `dummy_qtl_data`
# fixture (R/sysdata.rda, generated by dev/generate_dummy_qtl_data.R).
#
# `dummy_qtl_data` stores raw matrices rather than live bigsnp/bigpheno
# objects because bigstatsr FBMs are backed by a file on disk that is not
# part of the serialized R6 object -- an FBM saved into a .rda would point
# at a backing file that no longer exists once R CMD check unpacks the
# package elsewhere. So we keep the raw ingredients and re-wrap them in a
# fresh FBM every time a test needs them, matching the pattern already used
# by `make_qtl_test_data()` in test-run_conditional_eqtl.R.
#
# 5 phenotypes on chromosome 1 ("pheno1".."pheno5") with 3, 2, 1, 0, 0
# independent causal signals respectively, each with a couple of LD-friend
# SNPs (variable r^2) that should NOT survive conditioning on the true
# causal SNP. See dummy_qtl_data$ground_truth for the exact causal SNPs,
# effect sizes, and friend/r^2 mapping.
load_dummy_qtl_data <- function(sample_order = NULL) {

  # FBM.code256 (not a plain FBM) is required here, not just as_FBM(): the
  # bigQTL() gap this fixture targets exercises compute_geno_pcs(), which
  # calls bigsnpr::snp_autoSVD() -- that function requires genotypes stored
  # as FBM.code256, the same class bigsnpr itself uses for real bigSNP
  # objects.
  geno_fbm <- bigstatsr::FBM.code256(
    nrow = nrow(dummy_qtl_data$geno), ncol = ncol(dummy_qtl_data$geno),
    code = bigsnpr::CODE_012
  )
  geno_fbm[, ] <- dummy_qtl_data$geno

  bigsnp <- list(
    genotypes = geno_fbm,
    fam       = dummy_qtl_data$fam,
    map       = dummy_qtl_data$map
  )

  bigpheno <- bigPheno(dummy_qtl_data$pheno)

  design_base <- dummy_qtl_data$design_base

  if (!is.null(sample_order)) {
    design_base <- design_base[sample_order, , drop = FALSE]
  }

  list(
    bigsnp       = bigsnp,
    bigpheno     = bigpheno,
    pheno_coord  = dummy_qtl_data$pheno_coord,
    design_base  = design_base,
    ground_truth = dummy_qtl_data$ground_truth,
    sample_ids   = dummy_qtl_data$fam$sample.ID
  )
}
